networks:
  ddos-net:
    driver: bridge

services:
  # Zookeeper (cần thiết cho Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    networks:
      - ddos-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka (message broker)
  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    networks:
      - ddos-net
    ports:
      - "29092:29092"
    volumes:
      - ./kafka_producer:/home/appuser
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "ddos_packets_raw:1:1"

  # Spark Master
  spark-master:
    image: bitnami/spark:3.3
    container_name: spark-master
    networks:
      - ddos-net
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark_app:/opt/spark-apps
      - ./data:/opt/spark-data
    environment:
      - SPARK_MODE=master
      - HOME=/tmp

  # Spark Worker
  spark-worker:
    image: bitnami/spark:3.3
    container_name: spark-worker
    networks:
      - ddos-net
    depends_on:
      - spark-master
    volumes:
      - ./spark_app:/opt/spark-apps
      - ./data:/opt/spark-data
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - HOME=/tmp
      - SPARK_MASTER_URL=spark://spark-master:7077 # Chỉ cho worker biết master ở đâu
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  producer:
    build:
      context: ./producer          # Thư mục chứa Dockerfile, script, v.v.
    container_name: kafka-producer
    depends_on:
      - kafka
    networks:
      - ddos-net
    volumes:
      - ./data:/data  # Mount dữ liệu từ người tiền xử lý    